### ISSUE TITLE
V2.0.8 特写语法创建索引时，未检测影响条数

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning-go#11]
V2.0.8 ，以语法 "create index <index_name> on <table_name> (columns)" 创建索引时，检测给出的影响条数为0，无法限制DDL影响条数。

**Comment by cookieY** [comment]
@yuandajn578  影响行数是根据explain进行分析。由于explain并不支持此类DDL语句，所以无法实现该功能

**Comment by yuandajn578** [comment]
@cookieY  能否检测时拒绝这种不规范的DDL语法？

**Comment by cookieY** [comment]
暂时无法拒绝
