### ISSUE TITLE
V2.0.8 不支持create table like 语法

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning-go#15]
V2.0.8 ，审核规则中设置了允许主键非int/bigint，创建表时，使用语法 create table t2 like  t1，t1表只有一个UUID主键，但检测报错“不正确的表定义！没有主键/有多个自增列！”

**Comment by cookieY** [comment]
@yuandajn578  审核平台应该是用来审核相关开发的业务SQL 

对于这种非业务功能性SQL 我个人建议直接走人工即可。

没必要什么sql都往平台上送。

**Comment by yuandajn578** [comment]
是想尽量解放人力

**Comment by cookieY** [comment]
很抱歉,任何的工具都不可能满足所有的人的需求.
