### ISSUE TITLE
V2.0.8 表添加字段不支持标准 after 语法

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning-go#16]
V2.0.8  表添加多个字段时，如果使用标准语法的 after 关键字使用了这些新字段，则报错“列不存在”。
![image](https://user-images.githubusercontent.com/54062997/63745140-07250780-c8d4-11e9-8f5a-283b9b1b927d.png)

**Comment by cookieY** [comment]
@yuandajn578 审核系统会检测目前已存在的字段，并不允许不存在的字段依赖另外一个不存在的字段

![image](https://user-images.githubusercontent.com/22343354/63746808-3b9ac280-c8d8-11e9-8777-91c19f19b66a.png)

**Comment by yuandajn578** [comment]
@cookieY 这是mysql原生的语法，直接执行是没问题的。

**Comment by cookieY** [comment]
并没有说这个语法是有问题，而是平台并不支持这种写法

**Comment by yuandajn578** [comment]
这种语法用的很多，能不能考虑支持啊？

**Comment by cookieY** [comment]
暂时不会考虑
