### ISSUE TITLE
V2.0.8  DDL不支持表的 rename 操作

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning-go#17]
V2.0.8  DDL不支持表的 rename 操作，这是经常用到的操作，可以考虑支持吗？

**Comment by cookieY** [comment]
支持表rename 请自行查看是否语句及配置有问题

**Comment by yuandajn578** [comment]
![image](https://user-images.githubusercontent.com/54062997/63760605-3480ae00-c8f2-11e9-97d3-413ee71a274c.png)

![image](https://user-images.githubusercontent.com/54062997/63760638-44988d80-c8f2-11e9-9118-4c2a1e14be3f.png)

**Comment by yuandajn578** [comment]
@cookieY 没发现哪里有问题啊，请不吝赐教。

**Comment by cookieY** [comment]
@yuandajn578 很抱歉 这是一个Bug。会在下个版本修复
