### ISSUE TITLE
查询导出权限是否可以按照用户来分配

### ISSUE THREAD

**Issue by CarlXK** [cookieY/Yearning-go#19]
查询导出权限是否可以按照用户来分配

**Comment by cookieY** [comment]
@CarlXK 开启审核查询之后,所有用户的工单都会交由管理员审批,管理员可以选择是否给用户查询的权限.可以满足你的要求。 对于不开启查询审核直接用户分配，将来会增加

**Comment by yuandajn578** [comment]
顶
