### ISSUE TITLE
V2.0.*版本：有一定概率出现已有的审核规则失效

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning-go#23]
V2.0.*版本：有一定概率出现已有的审核规则失效，即需要在”审核规则”页面点击“保存”后，已有的审核规则才能重新生效，此时日志可能会出现报错：
{"time":"2019-08-28T15:56:13.989840099+08:00","level":"ERROR","prefix":"echo","file":"general.go","line":"198","message":"Error 1103: Incorrect table name ''"}
(/var/jenkins_home/workspace/Yearning-go/src/handle/general.go:197) 
[2019-08-28 15:56:13]  Error 1103: Incorrect table name ''

**Comment by cookieY** [comment]
请描述具体场景及复现步骤，该错误信息和审核规则没关系。

**Comment by yuandajn578** [comment]
目前不好复现，下次再遇到时再看错误日志吧，不一定报错。

**Comment by cookieY** [comment]
@yuandajn578 有可能是你双开检测,或者其他的问题。从代码角度来说 审核的规则只会在程序启动及变更时更新。其他地方不会对这个有任何操作
