### ISSUE TITLE
ldap 出错  {"time":"2019-08-28T21:26:55.629099572+08:00","level":"ERROR","prefix":"echo","file":"toolbox.go","line":"83","message":"LDAP Result Code 200 \"Network Error\": dial tcp: address ldap://192.168.121.25:389: too many colons in address"}

### ISSUE THREAD

**Issue by topicgit** [cookieY/Yearning-go#24]
{"time":"2019-08-28T21:26:55.629099572+08:00","level":"ERROR","prefix":"echo","file":"toolbox.go","line":"83","message":"LDAP Result Code 200 \"Network Error\": dial tcp: address ldap://192.168.121.25:389: too many colons in address"}

这是什么原因？ 前面是失败。

**Comment by topicgit** [comment]
![图片](https://user-images.githubusercontent.com/11975460/63861251-1e035100-c9dd-11e9-8691-3245dee8f236.png)

**Comment by topicgit** [comment]
我其他系统也是这么连接， 就是可以的

**Comment by cookieY** [comment]
去掉ldap://

**Comment by topicgit** [comment]
> 去掉ldap://

可以了 多谢🙏  @cookieY
