### ISSUE TITLE
页面优化建议-提升用户体验

### ISSUE THREAD

**Issue by topicgit** [cookieY/Yearning-go#26]
![image](https://user-images.githubusercontent.com/11975460/63908653-86d8e080-ca52-11e9-9b02-f85f1d492a40.png)

**Comment by topicgit** [comment]
建议，第二列也可以隐藏 ， 这样查询的SQL结果就能全屏展示

**Comment by cookieY** [comment]
@topicgit 已合并2.1.1功能
