### ISSUE TITLE
阿里云POLARDB开启备份后执行sql失败，报Binlog异常

### ISSUE THREAD

**Issue by sunnywalden** [cookieY/Yearning-go#27]
条件：
       1.版本yearning-go v2.0.9
       2.数据库为阿里云POLARDB
复现步骤：  
       1.提交DML或DDL工单并开启备份；
       2.工单审核通过后，执行工单；
问题：
        1.工单执行状态为“执行失败”；
         2.后端日志报“/var/jenkins_home/workspace/Yearning-go/src/parser/roll.go:590: Binlog没有开启无法备份!!”；

**Comment by cookieY** [comment]
错误提示很明显，没有开启binlog
