### ISSUE TITLE
V2.1.0 新用户注册后，点击登录，无反应，或提示“用户名/密码错误”，后台报错

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning-go#29]
{"time":"2019-09-02T16:03:01.661676058+08:00","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] runtime error: index out of range goroutine 29 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0x13a02f8, 0x1000, 0x1210000, 0x1549fe0, 0xc000210240)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/middleware/recover.go:71 +0xf1\npanic(0x1183f00, 0x22dcfe0)\n\t/var/jenkins_home/go/src/runtime/panic.go:522 +0x1b5\nYearning-go/src/lib.PKCS7UnPadding(...)\n\t/var/jenkins_home/workspace/Yearning-go/src/lib/encrypt.go:115\nYearning-go/src/lib.Decrypt(0x0, 0x0, 0xc0000da000, 0x0)\n\t/var/jenkins_home/workspace/Yearning-go/src/lib/encrypt.go:101 +0x233\nYearning-go/src/handle.FetchQueryDatabaseInfo(0x1549fe0, 0xc000210240, 0x0, 0x0)\n\t/var/jenkins_home/workspace/Yearning-go/src/handle/query.go:127 +0x53f\ngithub.com/labstack/echo/v4/middleware.JWTWithConfig.func2.1(0x1549fe0, 0xc000210240, 0x20, 0x1216180)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/middleware/jwt.go:181 +0x386\ngithub.com/labstack/echo/v4.(*Echo).add.func1(0x1549fe0, 0xc000210240, 0xc000192120, 0x150f080)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/echo.go:506 +0x87\ngithub.com/labstack/echo/v4/middleware.GzipWithConfig.func1.1(0x1549fe0, 0xc000210240, 0x0, 0x0)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/middleware/compress.go:92 +0x1e4\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1(0x1549fe0, 0xc000210240, 0x0, 0x0)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/middleware/recover.go:78 +0xd5\ngithub.com/labstack/echo/v4/middleware.SecureWithConfig.func1.1(0x1549fe0, 0xc000210240, 0x3, 0x4)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/middleware/secure.go:134 +0x49f\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0002f8000, 0x150f080, 0xc0002f62a0, 0xc0003ce100)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/echo.go:617 +0x22d\nnet/http.serverHandler.ServeHTTP(0xc000442c30, 0x150f080, 0xc0002f62a0, 0xc0003ce100)\n\t/var/jenkins_home/go/src/net/http/server.go:2774 +0xa8\nnet/http.(*conn).serve(0xc0000ac0a0, 0x1515700, 0xc000086040)\n\t/var/jenkins_home/go/src/net/http/server.go:1878 +0x851\ncreated by net/http.(*Server).Serve\n\t/var/jenkins_home/go/src/net/http/server.go:2884 +0x2f4\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f197235ee38, 0x72, 0x0)\n\t/var/jenkins_home/go/src/runtime/netpoll.go:182 +0x56\ninternal/poll.(*pollDesc).wait(0xc0003aa098, 0x72, 0x0, 0x0, 0x13329d5)\n\t/var/jenkins_home/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b\ninternal/poll.(*pollDesc).waitRead(...)\n\t/var/jenkins_home/go/src/internal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Accept(0xc0003aa080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/var/jenkins_home/go/src/internal/poll/fd_unix.go:384 +0x1ba\nnet.(*netFD).accept(0xc0003aa080, 0xb4, 0x203000, 0x203000)\n\t/var/jenkins_home/go/src/net/fd_unix.go:238 +0x42\nnet.(*TCPListener).accept(0xc0003566d8, 0xc000050a00, 0x40d569, 0xc000132140)\n\t/var/jenkins_home/go/src/net/tcpsock_posix.go:139 +0x32\nnet.(*TCPListener).AcceptTCP(0xc0003566d8, 0x3818d879, 0xa18b6b5d565ce022, 0x44c348)\n\t/var/jenkins_home/go/src/net/tcpsock.go:247 +0x48\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept(0xc0003566d8, 0xc0000bbc90, 0x4b4ac6, 0x5d6cccb3, 0x437a3f)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/echo.go:821 +0x2f\nnet/http.(*Server).Serve(0xc000442c30, 0x150c080, 0xc0003566e0, 0x0, 0x0)\n\t/var/jenkins_home/go/src/net/http/server.go:2859 +0x22d\ngithub.com/labstack/echo/v4.(*Echo).StartServer(0xc0002f8000, 0xc000442c30, 0xc0000bbf38, 0x1)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/echo.go:708 +0x388\ngithub.com/labstack/echo/v4.(*Echo).Start(...)\n\t/var/jenkins_home/go/pkg/mod/github.com/labstack/echo/v4@v4.1.5/echo.go:628\nYearning-go/src/service.StartYearning(0x7ffe74a427fb, 0x4, 0x7ffe74a427db, 0x1c)\n\t/var/jenkins_home/workspace/Yearning-go/src/service/yearning.go:46 +0x623\nmain.main()\n\t/var/jenkins_home/workspace/Yearning-go/main.go:73 +0xd5\n\ngoroutine 5 [select]:\ndatabase/sql.(*DB).connectionOpener(0xc0000d0540, 0x1515700, 0xc00016a980)\n\t/var/jenkins_home/go/src/datab\n"}

**Comment by cookieY** [comment]
@yuandajn578 此错误与登录接口无关,实测注册登录接口无问题。请检查环境及配置
