### ISSUE TITLE
V2.1.0 源码包[Source code.zip]内容不包含源码

### ISSUE THREAD

**Issue by yuandajn578** [cookieY/Yearning-go#30]
![image](https://user-images.githubusercontent.com/54062997/64227886-b33fa180-cf17-11e9-8b38-6da523a872f8.png)

**Comment by cookieY** [comment]
源码直接下载master分支即可

**Comment by yuandajn578** [comment]
@cookieY master分支不是最新的吧

**Comment by cookieY** [comment]
@yuandajn578 源码只在大版本更新时更新。
