### ISSUE TITLE
[使用建议]建议提供LDAP的配置示例

### ISSUE THREAD

**Issue by uiwe** [cookieY/Yearning-go#31]
我们使用的是AD账号，在配置LDAP的时候一直不成功，建议提供一个配置建议。我们的运维小伙伴反馈当前的LDAP配置跟Jenkins等配置不一样，令人困惑。

**Comment by cookieY** [comment]
@uiwe  可以参考grafana的ldap配置

**Comment by uiwe** [comment]
![a](https://user-images.githubusercontent.com/3055201/64331515-836ec780-d005-11e9-8e59-1cc36a85c6b1.png)


示例如上吧。ldap地址栏不需要添加ldap 协议头。
