### ISSUE TITLE
【Bug】数据库连接上存在问题

### ISSUE THREAD

**Issue by uiwe** [cookieY/Yearning-go#33]
目前的问题
数据库连接失败，密码中包含敏感词“@”

如何解决
Yearning-go\src\handle\dbmanage.go 的162行
_, e := gorm.Open("mysql", fmt.Sprintf("%s:%s@(%s:%d)/?charset=utf8&parseTime=True&loc=Local", u.User, u.Password, u.Ip, u.Port)) 如果user 或者password中有“：”或者“@”字符会导致连接失败。

可以使用&username=%s&password=%s 同时转义&字符。

问题2. 测试连接之后需要断开连接。目前未发现断开代码。defer DB.close()

**Comment by cookieY** [comment]
@ 字符不会导致出现问题  : 号会导致出现此类问题。 是否有详细的case ？
