### ISSUE TITLE
提交DML工单审批后无法查看回滚语句

### ISSUE THREAD

**Issue by mafeicnnui** [cookieY/Yearning-go#34]
**目前的问题**

     版本：Yearning-2.1.1
     问题：提交DML工单，审批后无法查看回滚语句

     
**操作步骤：**
1. 提交DML工单（单条，或批量INSERT）
2. 审核人登陆：工单->审批->选择执行人->检测sql->同意
3. 执行人登陆：审核->工单->审批->检测sql->执行->执行成功
4.  执行人登陆：审核->工单->执行结果->选中SQL->查看回滚语句->当前检查sql(暂无数据)->填写工单说明->提交工单

![1](https://user-images.githubusercontent.com/13817818/64594171-0d41da80-d3e2-11e9-969b-a086327821e6.png)

![2](https://user-images.githubusercontent.com/13817818/64594185-15017f00-d3e2-11e9-8339-2b3489319819.png)

5.  审核人登陆：审核->工单->审批->选择执行人->检测sql(按钮无响应)

![3](https://user-images.githubusercontent.com/13817818/64594190-19c63300-d3e2-11e9-8ad2-4bc3bd2e227d.png)

**说明：**DDL单条或批量也是上述操作未发现问题。

**Comment by cookieY** [comment]
@mafeicnnui https://guide.yearning.io/attention.html

**Comment by mafeicnnui** [comment]
非常感谢，问题已解决！
