### ISSUE TITLE
yearning导出的数据的时候把 json里面的逗号 "," 变成分隔符了

### ISSUE THREAD

**Issue by changeflyhigh** [cookieY/Yearning-go#38]
**目前的问题**
mysql 字段 result_json 的其中一行数据 为 {"a":"1", "b": "2"}
导出后这行数据被拆分成两个字段数据  a:1 和 b: 2 分布在两列中

**如何解决**
在导出表格的时候, 设置分隔符 为 Tab, 逗号, 分号等等

**最终效果**
mysql 字段 result_json 的数据  {"a":"1", "b": "2"} 导出到表格后, 应该在同一列中

**Comment by cookieY** [comment]
csv格式默认采用逗号作为分隔符。目前来说对于该格式没有什么好的处理办法
