### ISSUE TITLE
yearning导出查询到的数据后, 身份证号和手机号会变成 科学计算来表示

### ISSUE THREAD

**Issue by changeflyhigh** [cookieY/Yearning-go#39]
**目前的问题**
yearning导出查询到的数据
身份证号会变成  4.40981E+17 , 号码最后几位会变成 0

**如何解决**
导出的时候, 在字段中加上单引号 ' ,这样子身份证号&手机号会变成字符串类型, 不会被识别为数字

**最终效果**
身份证号和手机号 不再显示为科学计算法样式

**Comment by cookieY** [comment]
此为csv格式文档并不是excel
