### ISSUE TITLE
提交工单和查询页面中`填写SQL语句`输入框输入错位

### ISSUE THREAD

**Issue by go-xmyang** [cookieY/Yearning-go#4]
如下图，在输入SQL的时候，光标前移错位，只有数字和字母会出现这个情况，全输入中文则不会，是否是字符的宽度计算有误？
![image](https://user-images.githubusercontent.com/29217985/63311940-62825300-c332-11e9-88fd-6946ca7ba653.png)

**Comment by cookieY** [comment]
![image](https://user-images.githubusercontent.com/22343354/63397430-1b14c900-c3fd-11e9-82a0-3eebe5d001bc.png)
未复现此问题，请使用Chrome浏览器最新版本进行复现

**Comment by go-xmyang** [comment]
你好，我的Chrome版本是最新版本：
![image](https://user-images.githubusercontent.com/29217985/63407297-bcf8dd80-c41e-11e9-881d-22a5490ac3b5.png)
![image](https://user-images.githubusercontent.com/29217985/63407606-7657b300-c41f-11e9-9e12-f45370be3464.png)

使用firefox也出现了同样的问题：
![image](https://user-images.githubusercontent.com/29217985/63407559-5c1dd500-c41f-11e9-8546-42d74d22e2c8.png)

**Comment by go-xmyang** [comment]
经过测试，我同事的电脑也没有出现此问题，应该我的电脑哪里有问题。

**Comment by cookieY** [comment]
@go-xmyang 可能与操作系统平台有关  你同事是mac 么

**Comment by go-xmyang** [comment]
也是windows10，我自己也是windows10。
![image](https://user-images.githubusercontent.com/29217985/63408231-1eba4700-c421-11e9-83da-de8360464ca6.png)

**Comment by cookieY** [comment]
@go-xmyang 可能存在个别环境不兼容的现象

**Comment by go-xmyang** [comment]
@cookieY 好的，谢谢。
