### ISSUE TITLE
ldap配置是不是应该加上ObjectClass配置，默认程序中使用objectClass=organizationalPerson，这个不是所有公司都用的是这个。

### ISSUE THREAD

**Issue by zhuleiandy888** [cookieY/Yearning-go#41]
/src/lib/toolbox.go：   109 行

    searchRequest := ldap.NewSearchRequest(
		l.Sc,
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		fmt.Sprintf("(&(objectClass=organizationalPerson)%s)", s),          #此处
		[]string{"dn"},
		nil,
	)

![image](https://user-images.githubusercontent.com/13164631/65654773-7feebf00-e04c-11e9-8b49-22eabbfaeef0.png)

另外建议：
      Search filter  做成配置项，去掉 “LDAP搜索规则“ 选择框，  做成文本框，让用户填写，这样自由度大没用限制。

**Comment by zhuleiandy888** [comment]
咋没动静了？  这个是刚需啊。

**Comment by cookieY** [comment]
@zhuleiandy888 已采纳 感谢提交建议
