### ISSUE TITLE
没有种cookie吗？登陆之后再次打开还是要求登陆。

### ISSUE THREAD

**Issue by zhuleiandy888** [cookieY/Yearning-go#43]
chrome ：  版本 77.0.3865.90（正式版本）

**Comment by cookieY** [comment]
关闭浏览器标签及关闭浏览器是会要求再次登录的。 cookie不安全

**Comment by zhuleiandy888** [comment]
在同一个游览器下，开多个窗口，已经登陆的情况下， 新开的窗口还是要求登陆。
可以关闭游览器之后再要求登陆 。
另外能不能提供一份完整的源码，我们公司希望做二次开发，包括前后端的。

**Comment by cookieY** [comment]
不支持同浏览器多用户登录。 二次开发问题请参考 https://guide.yearning.io/developer.html

**Comment by zhuleiandy888** [comment]
这个二次开发，还要自己实现sql审计逻辑，我的意思是，能不能提供一份包含sql审计引擎的完整项目代码。我们自行修改前段和后端代码，然后定制化编译。

**Comment by cookieY** [comment]
@zhuleiandy888 很抱歉，文档已经说明。
