### ISSUE TITLE
question - did it's supported pt-online-schema-changes ?

### ISSUE THREAD

**Issue by imiskolee** [cookieY/Yearning-go#9]
hi,team:

did it supported pt-online-schema-changes ? because the table will be locked when we using xtra db cluster,even mysql 5.7.

**Comment by cookieY** [comment]
Of course ,Yearning-go supported pt-osc. u can choice setting page setting  some pt-osc configuration.

**Comment by imiskolee** [comment]
@cookieY amazing! thanks for it.  i will be trying to test it now.
